### ISSUE TITLE
CKEditor Uncaught type error on some pages but not others

### ISSUE THREAD

**Issue by MordantWastrel** [MasaCMS/MasaCMS#101]
On some pages (but not most pages) we are unable to 'publish' or even 'view source' from CKEditor because we get the following error when attempting either:

```
plugin.js?t=J0BE:63 Uncaught TypeError: tools.object.keys is not a function
    at Object.left (plugin.js?t=J0BE:63:49)
    at r (ckeditor.js:232:203)
    at z (ckeditor.js:225:346)
    at ckeditor.js:237:209
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:313:331)
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:313:432)
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:313:432)
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:313:432)
    at CKEDITOR.filter.applyTo (ckeditor.js:237:3)
    at a.<anonymous> (ckeditor.js:334:278)
```

The inability to view source makes it difficult to post what the content of the page is, but here it is in non-admin view: https://wssl.org/programs/red-bulls-curriculum/

**Comment by MordantWastrel** [comment]
The culprit was the `colorbutton` plugin, which has this error even in the current release. We fixed it and the problem went away. Thank you!
