### ISSUE TITLE
rel shadowbox Displaying weird

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#185]
So I don't know if it is just me, but I have two sites that are on the latest version of MASA one is just using the Included Bootstrap template.  The Shadowbox element, when someone clicks on an image to see a larger version of the image, seems to get anchored to the top of and left of the page.  

The image below is from one of the sites. as you can see the image is on the left and cropped off.  
![image](https://user-images.githubusercontent.com/1850313/234128436-15e436b9-5f13-4cf7-9ab5-e5b05d3c888c.png)

This is from another site that I am developing and it does the same thing where the image is al the way at the top instead of the way is should be which is centered in the middle of the screen. 
![image](https://user-images.githubusercontent.com/1850313/234128632-ebc4719f-f1e9-4156-8e62-1d4a8c0996d1.png)

I haven't had this happen before. It is weird. 

Here is another site older of course where it works fine. 
![image](https://user-images.githubusercontent.com/1850313/234128766-ea03a713-0202-40a8-afb9-569021e05150.png)
Any ideas would be greatly appreciated.  

The two sites where I am having an issue are:
The URLs have spacing in them so they don't get indexed by Google by having them here as they are not live yet.  

https:// www.cobraheatshield.com/ index.cfm/product/chrome-plated-heat-shield/

https:// dev.grandchamber.org/about/ board-of-directors/

**Comment by Tigerlady** [comment]
Does anyone possibly have a solution for this?  Or put me in the right direction.  I am hoping to finalize the chamber site, but the have several galleries that will depend on the shadowbox working properly.  Thanks.

**Comment by Tigerlady** [comment]
Ok, so I have done a bit more digging.  I swapped out the shadowbox CSS and JS files with the latest version of the shadowbox. The shadowbox works but throws errors because declared masa variables are missing.  I am not skilled enough in JS to figure this out, but I will put the console errors here. Hopefully, someone can help me out.  

I got the latest version here on GitHub https://github.com/mjackson/shadowbox

The new version is /**
   * The current version of Shadowbox.
   */
  shadowbox.version = "4.0.0";

It works; it is also ugly and missing titles, but it works.  However, I am sure that this is also breaking other Masa items. 
Please, if someone has a fix, post it here.  Thank you.

**Console Errors**
caught TypeError: Cannot read properties of undefined (reading 'init')
    at Arguments.<anonymous> (core.js:1527:22)
    at Object.load (loader.js:303:11)
    at Arguments.<anonymous> (loader.js:149:15)
    at Object.load (loader.js:303:11)
    at loader.js:149:15
    at Object.<anonymous> (loader.js:214:8)
    at HTMLScriptElement.cb (loader.js:221:6)
(anonymous) @ core.js:1527
load @ loader.js:303
(anonymous) @ loader.js:149
load @ loader.js:303
(anonymous) @ loader.js:149
(anonymous) @ loader.js:214
cb @ loader.js:221
load (async)
appendElmt @ loader.js:77
loadjs @ loader.js:225
load @ loader.js:47
load @ loader.js:304
load @ loader.js:137
load @ loader.js:304
initShadowBox @ core.js:1520
processors @ core.js:2031

**Comment by jeroenweareorangeeu** [comment]
Hello @Tigerlady 
Is this issue still relevant or did you find a solution?
This ticket will be closed after 30th September 2024 if no further comment is provided.

Greetings,

Jeroen

**Comment by Tigerlady** [comment]
The issue persists. I have found another solution, but I am not completely happy with it, as extra JS code is required to be loaded to the pages. Using Shadowbox to open a larger image was just so easy until this update.
