### ISSUE TITLE
Error when razuna not set in settings.ini.cfm

### ISSUE THREAD

**Issue by guustnieuwenhuis** [MasaCMS/MasaCMS#220]
**Describe the bug**
When `razuna` is not set in the settings.ini.cfm file, this throws an error in some cases when a content node is saved.

**Expected behavior**
No error is thrown.

**Additional context**

500 Error
Can't cast String [] to a boolean
Code:0
Type:expression
lucee.runtime.exp.CasterException: Can't cast String [] to a boolean
	at lucee.runtime.op.Caster.toBooleanValue(Caster.java:288)
	at lucee.runtime.op.Caster.toBooleanValue(Caster.java:261)
	at content.file.razuna.razunasettingsbean_cfc$cf.udfCall(/mura/content/file/razuna/razunaSettingsBean.cfc:14)

**Comment by guustnieuwenhuis** [comment]
fixed in release 7.4.3
