### ISSUE TITLE
Filebrowser in Admin does not work

### ISSUE THREAD

**Issue by sebgmc** [MasaCMS/MasaCMS#258]
We log into the Admin and then try and open the filebrowser from the menu on the left. Nothing happens, but "under the hood" this  call is made (kind of weird this call can be made even when not logged in...):

[[pathtosite]/_api/json/v1/new-nl/filebrowser//browse?resourcepath=User_Assets&directory=&settings=1&]([pathtosite]/_api/json/v1/new-nl/filebrowser/browse?resourcepath=User_Assets&directory=&settings=1&)

There we get this error:

"component [muraWRM.core.modules.v1.filebrowser.model.beans.filebrowser] has no function with name [getPrimaryKey]"

Which is kind of weird because in the filebrowser.cfc it says this:
 
```
component
      entityname="filebrowser"
      extends="mura.bean.bean"
      displayname="Mura File Browser"
      table="m_filebrowser"
      public="true"
      {
}
```
 
So it extends the mura.bean.bean, which does have a getPrimaryKey function:
 
```
function getPrimaryKey(){
      return variables.primarykey;
}
```

Sidenote: the referenced table does not exist in our MASA CMS database, but it never has. Probably does something else than I think it does ;-)

For now we cannot use the filebrowser, and hence no more images etc for our content. We're on the latest version of MASA CMS (v.7.4.x) and have upgraded from MURA CMS 7.1.x.

Running on Windows servers. Errors occurs on all devices.

The stacktrace:
```
{
           "error": {
        "message": "Unhandled Exception",
        "code": "server_error",
        "stacktrace": {
        "extended_info": "",
        "message": "component [muraWRM.core.modules.v1.filebrowser.model.beans.filebrowser] has no function with name [getPrimaryKey]",
        "detail": "",
        "additional": { },
        "tagcontext": [
          {
            "raw_trace": "client.api.json.v1.apiutility_cfc$cf.udfCall2(/mura/client/api/json/v1/apiUtility.cfc:1230)",
            "codeprintplain": "1228: \t\t\t\t\t\tvar primaryKey=application.objectMappings['#params.entityName#'].primaryKey;\n1229: \t\t\t\t\t} else if (getServiceFactory().containsBean(params.entityname)){\n1230: \t\t\t\t\t\tvar primaryKey=getBean(params.entityname).getPrimaryKey();\n1231: \t\t\t\t\t} else {\n1232: \t\t\t\t\t\tvar primaryKey='undefined';\n",
            "column": "0",
            "line": "1230",
            "template": "[pathtosite]\\htdocs\\core\\mura\\client\\api\\json\\v1\\apiUtility.cfc",
            "id": "??",
            "type": "cfml",
            "codeprinthtml": "1228: \t\t\t\t\t\tvar primaryKey=application.objectMappings['#params.entityName#'].primaryKey;<br>\n1229: \t\t\t\t\t} else if (getServiceFactory().containsBean(params.entityname)){<br>\n<b>1230: \t\t\t\t\t\tvar primaryKey=getBean(params.entityname).getPrimaryKey();</b><br>\n1231: \t\t\t\t\t} else {<br>\n1232: \t\t\t\t\t\tvar primaryKey='undefined';<br>\n"
        },
          {
            "raw_trace": "content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:613)",
            "codeprintplain": "611: \t\t\t<cfset siteid=\"default\">\n612: \t\t</cfif>\n613: \t\t<cfreturn getBean('settingsManager').getSite(siteid).getApi('json','v1').processRequest(arguments.path)>\n614: \t<cfelseif left(arguments.path,len(restendpoint)) eq restendpoint or left(arguments.path,len(restendpoint)) eq restendpoint>\n615: \t\t<cfset request.muraAPIRequest=true>\n",
            "column": "0",
            "line": "613",
            "template": "[pathtosite]\\htdocs\\core\\mura\\content\\contentServer.cfc",
            "id": "??",
            "type": "cfml",
            "codeprinthtml": "611: \t\t\t&lt;cfset siteid=&quot;default&quot;&gt;<br>\n612: \t\t&lt;/cfif&gt;<br>\n<b>613: \t\t&lt;cfreturn getBean('settingsManager').getSite(siteid).getApi('json','v1').processRequest(arguments.path)&gt;</b><br>\n614: \t&lt;cfelseif left(arguments.path,len(restendpoint)) eq restendpoint or left(arguments.path,len(restendpoint)) eq restendpoint&gt;<br>\n615: \t\t&lt;cfset request.muraAPIRequest=true&gt;<br>\n"
        },
          {
            "raw_trace": "content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:771)",
            "codeprintplain": "769: \n770: \t<cfif listFindNoCase('_api,tasks',listFirst(path,'/'))>\n771: \t\t<cfreturn handleAPIRequest(path)>\n772: \t<cfelse>\n773: \n",
            "column": "0",
            "line": "771",
            "template": "[pathtosite]\\htdocs\\core\\mura\\content\\contentServer.cfc",
            "id": "??",
            "type": "cfml",
            "codeprinthtml": "769: <br>\n770: \t&lt;cfif listFindNoCase('_api,tasks',listFirst(path,'/'))&gt;<br>\n<b>771: \t\t&lt;cfreturn handleAPIRequest(path)&gt;</b><br>\n772: \t&lt;cfelse&gt;<br>\n773: <br>\n"
        },
          {
            "raw_trace": "index_cfm$cf.call(/index.cfm:75)",
            "codeprintplain": "73: modified version; it is your choice whether to do so, or to make such modified version available under the GNU General Public License \n74: version 2 without this exception. You may, if you choose, apply this exception to your own modified versions of Mura CMS.\n75: ---><cfoutput>#application.contentServer.handleRootRequest()#</cfoutput>\n",
            "column": "0",
            "line": "75",
            "template": "[pathtosite]\\htdocs\\index.cfm",
            "id": "??",
            "type": "cfml",
            "codeprinthtml": "73: modified version; it is your choice whether to do so, or to make such modified version available under the GNU General Public License <br>\n74: version 2 without this exception. You may, if you choose, apply this exception to your own modified versions of Mura CMS.<br>\n<b>75: ---&gt;&lt;cfoutput&gt;#application.contentServer.handleRootRequest()#&lt;/cfoutput&gt;</b><br>\n"
        }
        ],
        "errorcode": "0",
        "errnumber": "0",
        "type": "expression",
        "stacktrace": "component [muraWRM.core.modules.v1.filebrowser.model.beans.filebrowser] has no function with name [getPrimaryKey]\r\n\tat lucee.runtime.type.util.ComponentUtil.notFunction(ComponentUtil.java:667):667\r\n\tat lucee.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:567):567\r\n\tat lucee.runtime.ComponentImpl._call(ComponentImpl.java:526):526\r\n\tat lucee.runtime.ComponentImpl.call(ComponentImpl.java:1763):1763\r\n\tat lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:745):745\r\n\tat lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1601):1601\r\n\tat client.api.json.v1.apiutility_cfc$cf.udfCall2(/mura/client/api/json/v1/apiUtility.cfc:1230):1230\r\n\tat client.api.json.v1.apiutility_cfc$cf.udfCall(/mura/client/api/json/v1/apiUtility.cfc):-1\r\n\tat lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112):112\r\n\tat lucee.runtime.type.UDFImpl._call(UDFImpl.java:329):329\r\n\tat lucee.runtime.type.UDFImpl.call(UDFImpl.java:230):230\r\n\tat lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642\r\n\tat lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524\r\n\tat lucee.runtime.ComponentImpl.call(ComponentImpl.java:1763):1763\r\n\tat lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:745):745\r\n\tat lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1601):1601\r\n\tat content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:613):613\r\n\tat content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc):-1\r\n\tat lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112):112\r\n\tat lucee.runtime.type.UDFImpl._call(UDFImpl.java:329):329\r\n\tat lucee.runtime.type.UDFImpl.call(UDFImpl.java:230):230\r\n\tat lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766\r\n\tat lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:745):745\r\n\tat lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1601):1601\r\n\tat content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:771):771\r\n\tat content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc):-1\r\n\tat lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112):112\r\n\tat lucee.runtime.type.UDFImpl._call(UDFImpl.java:329):329\r\n\tat lucee.runtime.type.UDFImpl.call(UDFImpl.java:230):230\r\n\tat lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642\r\n\tat lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524\r\n\tat lucee.runtime.ComponentImpl.call(ComponentImpl.java:1763):1763\r\n\tat lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:745):745\r\n\tat lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1601):1601\r\n\tat index_cfm$cf.call(/index.cfm:75):75\r\n\tat lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:959):959\r\n\tat lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:911):911\r\n\tat lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:225):225\r\n\tat lucee.runtime.listener.ModernAppListener.onRequest(ModernAppListener.java:101):101\r\n\tat lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2276):2276\r\n\tat lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2239):2239\r\n\tat lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:460):460\r\n\tat lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:47):47\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:729):729\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291):291\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206\r\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239):239\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206\r\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217):217\r\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106):106\r\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502):502\r\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142):142\r\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79):79\r\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88):88\r\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518):518\r\n\tat org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:844):844\r\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673):673\r\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500):1500\r\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456):1456\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142):1142\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617):617\r\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61):61\r\n\tat java.lang.Thread.run(Thread.java:745):745\r\n",
        "extendedinfo": ""
    }
           },
           "method": "invalid",
           "apiversion": "v1"
}

```

**Comment by mhelsloot** [comment]
I have a small addition to this error, @sebgmc and me found that the filebrowser is working when go to files in the site you logged in to. After you use the "Site switcher" on top of the screen to go to an other site the filebrowser does not work anymore. In the developpertools we get this VUE error

TypeError: Cannot read properties of undefined (reading 'length')
    at a.eval (eval at wa (vue.min.js:6:85746), <anonymous>:3:622)
    at t._render (vue.min.js:6:33236)
    at a.r (vue.min.js:6:64842)
    at St.get (vue.min.js:6:16384)
    at St.run (vue.min.js:6:17268)
    at At (vue.min.js:6:15378)
    at Array.<anonymous> (vue.min.js:6:11663)
    at Ve (vue.min.js:6:11123)

Looks like MASA can not find the assets folder of the chosen site.

**Comment by jeroenweareorangeeu** [comment]
Hi,

Sorry for the very long delay.
Is this issue still relevant or did you find a solution?
Please let me know if we can close this ticket or not.

This ticket will be closed after 20th September 2024 if no further comment is provided.
Thank you.

Greetings,

Jeroen

**Comment by sebgmc** [comment]
Hi Jeroen, no actions taken helped, so in the end we installed a brand new
version of MASA CMS on Lucee 6.x and now all works peachy. Upgrading and
upgrading and upgrading on top of upgrades and moves is not a solid
solution on a production environment. Hopefully we won't have any similar
issues like this in the future. Kind regards, Sebastiaan Naafs - van Dijk

**Comment by jeroenweareorangeeu** [comment]
@sebgmc  Great to hear this. Will close this ticket.
