### ISSUE TITLE
Upgrading to Lucee 6.0.0.585 Release Breaks Masa

### ISSUE THREAD

**Issue by Tigerlady** [MasaCMS/MasaCMS#261]
**Describe the bug**
Last night, we upgraded one instance of Lucee (the one we use for development work) to Release 6.0.6.585

Afterwards, all of my dev sites using Masa broke, saying bean not found **utility**

**To Reproduce**
500 Error
bean not found: **utility**
Type: application
lucee.runtime.exp.CustomTypeException: bean not found: utility
	at lucee.runtime.tag.Throw._doStartTag(Throw.java:224)
	at lucee.runtime.tag.Throw.doStartTag(Throw.java:211)
	at bean.ioc_cfc$cf.udfCall1(/mura/bean/ioc.cfc:136)
	at bean.ioc_cfc$cf.udfCall(/mura/bean/ioc.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:356)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:701)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:589)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1993)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1777)
	at core.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/core/appcfc/onApplicationStart_include.cfm:390)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1058)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:950)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:931)
	at core.appcfc.onapplicationstart_method_cfm$cf.udfCall(/core/appcfc/onApplicationStart_method.cfm:81)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:356)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:701)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:589)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1993)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:446)
	at lucee.runtime.listener.ModernAppListener.onApplicationStart(ModernAppListener.java:308)
	at lucee.runtime.PageContextImpl.initApplicationContext(PageContextImpl.java:3179)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:124)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2494)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2480)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2451)
	at lucee.runtime.engine.Request.exe(Request.java:45)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1219)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1165)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at jdk.internal.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:134)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doNext(FusionReactorRequestHandler.java:698)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doHttpServletRequest(FusionReactorRequestHandler.java:256)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.doFusionRequest(FusionReactorRequestHandler.java:119)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorRequestHandler.handle(FusionReactorRequestHandler.java:736)
	at com.intergral.fusionreactor.j2ee.filter.FusionReactorCoreFilter.doFilter(FusionReactorCoreFilter.java:36)
	at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.intergral.fusionreactor.j2ee.filterchain.WrappedFilterChain.doFilter(WrappedFilterChain.java:71)
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.intergral.fusionreactor.agent.filter.FusionReactorStaticFilter.doFilter(FusionReactorStaticFilter.java:54)
	at com.intergral.fusionreactor.agent.pointcuts.NewFilterChainPointCut$1.invoke(NewFilterChainPointCut.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:422)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)

Column: 0
ID: ??
Line: 136
Raw Trace: bean.ioc_cfc$cf.udfCall1(/mura/bean/ioc.cfc:136)
Template: E:\Websites\dev.mydomain.com\www\core\mura\bean\ioc.cfc
Type: cfml

Column: 0
ID: ??
Line: 390
Raw Trace: core.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/core/appcfc/onApplicationStart_include.cfm:390)
Template: E:\Websites\dev.mydomain.com\www\core\appcfc\onApplicationStart_include.cfm
Type: cfml

Column: 0
ID: ??
Line: 81
Raw Trace: core.appcfc.onapplicationstart_method_cfm$cf.udfCall(/core/appcfc/onApplicationStart_method.cfm:81)
Template: E:\Websites\dev.mydomain.com\www\core\appcfc\onApplicationStart_method.cfm
Type: cfml

**Environment (please complete the following information):**
 - OS: 	Windows Server 2022 (10.0) 64bit
 - CFML Engine [ Lucee 6.0.0.585]  	Apache Tomcat/9.0.80
 - Database [MSSQL]

**Additional context**
This was working yesterday on Lucee 5.4.4.38

**Comment by jeroenweareorangeeu** [comment]
Hello Tigerlady,

I looked into this and it appears that some code in Masa has some illegal code constructs for Lucee 6.   Lucee 6 is stricter in checking the CFML code than Lucee 5 apparantly. 

I've created a pull request with changes for this:

https://github.com/MasaCMS/MasaCMS/pull/262

Perhaps you can take a look at it, and (manually) apply the changes Let me know if your Masa instance is succesfully running on Lucee 6 (or not).

**Comment by jeroenweareorangeeu** [comment]
Fixed in release 7.4.5.
