### ISSUE TITLE
Masa CMS 500 Error (tentity doesn't exist)

### ISSUE THREAD

**Issue by asimakos** [MasaCMS/MasaCMS#313]
Hello!

When i try to start a Masa CMS app, i get the following error

Table 'devices.tentity' doesn't exist
Datasource:devices
SQL:select * from tentity where dynamic=1

![image2](https://github.com/MasaCMS/MasaCMS/assets/15226087/4566c5f4-0c76-4ae1-a00f-42d0f4be6694)

I have already created a datasource named devices via lucee. Any idea what is wrong?

![image1](https://github.com/MasaCMS/MasaCMS/assets/15226087/f9d9330e-f0cc-4d53-bf36-1038900a7b34)

Regards

**Comment by jeroenweareorangeeu** [comment]
Try applying the db update by addding this to your URL:

`?appreload&reload=appreload&applydbupates=true`

Masa should start now.

**Comment by asimakos** [comment]
I just tried it and i am getting the following error

```
500 Error
Table 'devices.tentity' doesn't exist
Datasource:devices
SQL:select * from tentity where dynamic=1
Code:0
Type:database
lucee.runtime.exp.DatabaseException: Table 'devices.tentity' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:780)
	at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:320)
	at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:287)
	at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235)
	at lucee.runtime.tag.Query.executeDatasoure(Query.java:1135)
	at lucee.runtime.tag.Query._doEndTag(Query.java:700)
	at lucee.runtime.tag.Query.doEndTag(Query.java:566)
	at org.lucee.cfml.query_cfc$cf.udfCall(/org/lucee/cfml/Query.cfc:227)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:350)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:786)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1775)
	at org.lucee.cfml.query_cfc$cf.udfCall(/org/lucee/cfml/Query.cfc:37)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:350)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:213)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:699)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:586)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1952)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1794)
	at bean.beanfactory_cfc$cf.udfCall1(/mura/bean/beanFactory.cfc:269)
	at bean.beanfactory_cfc$cf.udfCall(/mura/bean/beanFactory.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:350)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:586)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1933)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1775)
	at core.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/core/appcfc/onApplicationStart_include.cfm:485)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1056)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:929)
	at core.appcfc.onapplicationstart_method_cfm$cf.udfCall(/core/appcfc/onApplicationStart_method.cfm:81)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:350)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:586)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1933)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:444)
	at lucee.runtime.listener.ModernAppListener.onApplicationStart(ModernAppListener.java:306)
	at lucee.runtime.PageContextImpl.initApplicationContext(PageContextImpl.java:3168)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:122)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2493)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2478)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2449)
	at lucee.runtime.engine.Request.exe(Request.java:45)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1216)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1162)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:54)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at runwar.undertow.SSLCertHeaderHandler.handleRequest(SSLCertHeaderHandler.java:161)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:175)
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at runwar.undertow.WelcomeFileHandler.handleRequest(WelcomeFileHandler.java:39)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at runwar.undertow.SiteDeployment$1.handleRequest(SiteDeployment.java:162)
	at io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:141)
	at io.undertow.server.handlers.DisallowedMethodsHandler.handleRequest(DisallowedMethodsHandler.java:62)
	at io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:113)
	at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(EncodingHandler.java:72)
	at runwar.undertow.LifecyleHandler.handleRequest(LifecyleHandler.java:143)
	at runwar.undertow.SiteDeployment$4.handleRequest(SiteDeployment.java:345)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)

Column: 0
ID: ??
Line: 227
Raw Trace: org.lucee.cfml.query_cfc$cf.udfCall(/org/lucee/cfml/Query.cfc:227)
Template: /org/lucee/cfml/Query.cfc
Type: cfml

Column: 0
ID: ??
Line: 37
Raw Trace: org.lucee.cfml.query_cfc$cf.udfCall(/org/lucee/cfml/Query.cfc:37)
Template: /org/lucee/cfml/Query.cfc
Type: cfml

Column: 0
ID: ??
Line: 269
Raw Trace: bean.beanfactory_cfc$cf.udfCall1(/mura/bean/beanFactory.cfc:269)
Template: C:\Commandbox\devices\core\mura\bean\beanFactory.cfc
Type: cfml

Column: 0
ID: ??
Line: 485
Raw Trace: core.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/core/appcfc/onApplicationStart_include.cfm:485)
Template: C:\Commandbox\devices\core\appcfc\onApplicationStart_include.cfm
Type: cfml

Column: 0
ID: ??
Line: 81
Raw Trace: core.appcfc.onapplicationstart_method_cfm$cf.udfCall(/core/appcfc/onApplicationStart_method.cfm:81)
Template: C:\Commandbox\devices\core\appcfc\onApplicationStart_method.cfm
Type: cfml

```

**Comment by asimakos** [comment]
Sorry i think a d is missing. I just inserted it and now i get the following

```
500 Error
Table 'devices.tcontentcomments' doesn't exist
Datasource:devices
SQL:select * from tcontentcomments where 0=1
Code:0
Type:database
lucee.runtime.exp.DatabaseException: Table 'devices.tcontentcomments' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:320)
	at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:287)
	at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235)
	at lucee.runtime.tag.Query.executeDatasoure(Query.java:1135)
	at lucee.runtime.tag.Query._doEndTag(Query.java:700)
	at lucee.runtime.tag.Query.doEndTag(Query.java:566)
	at dbupdates._5_0_408_cfm276$cf.call(/mura/dbUpdates/5.0.408.cfm:5)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1056)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:929)
	at configbean_cfc$cf.udfCalla(/mura/configBean.cfc:949)
	at configbean_cfc$cf.udfCall(/mura/configBean.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:350)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:586)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1933)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1775)
	at core.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/core/appcfc/onApplicationStart_include.cfm:418)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1056)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:929)
	at core.appcfc.onapplicationstart_method_cfm$cf.udfCall(/core/appcfc/onApplicationStart_method.cfm:81)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:350)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:586)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1933)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:444)
	at lucee.runtime.listener.ModernAppListener.onApplicationStart(ModernAppListener.java:306)
	at lucee.runtime.PageContextImpl.initApplicationContext(PageContextImpl.java:3168)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:122)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2493)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2478)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2449)
	at lucee.runtime.engine.Request.exe(Request.java:45)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1216)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1162)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:54)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at runwar.undertow.SSLCertHeaderHandler.handleRequest(SSLCertHeaderHandler.java:161)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:175)
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at runwar.undertow.WelcomeFileHandler.handleRequest(WelcomeFileHandler.java:39)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
	at runwar.undertow.SiteDeployment$1.handleRequest(SiteDeployment.java:162)
	at io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:141)
	at io.undertow.server.handlers.DisallowedMethodsHandler.handleRequest(DisallowedMethodsHandler.java:62)
	at io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:113)
	at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(EncodingHandler.java:72)
	at runwar.undertow.LifecyleHandler.handleRequest(LifecyleHandler.java:143)
	at runwar.undertow.SiteDeployment$4.handleRequest(SiteDeployment.java:345)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Unknown Source)

Column: 0
ID: ??
Line: 5
Raw Trace: dbupdates._5_0_408_cfm276$cf.call(/mura/dbUpdates/5.0.408.cfm:5)
Template: C:\Commandbox\devices\core\mura\dbUpdates\5.0.408.cfm
Type: cfml

Column: 0
ID: ??
Line: 949
Raw Trace: configbean_cfc$cf.udfCalla(/mura/configBean.cfc:949)
Template: C:\Commandbox\devices\core\mura\configBean.cfc
Type: cfml

Column: 0
ID: ??
Line: 418
Raw Trace: core.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/core/appcfc/onApplicationStart_include.cfm:418)
Template: C:\Commandbox\devices\core\appcfc\onApplicationStart_include.cfm
Type: cfml

Column: 0
ID: ??
Line: 81
Raw Trace: core.appcfc.onapplicationstart_method_cfm$cf.udfCall(/core/appcfc/onApplicationStart_method.cfm:81)
Template: C:\Commandbox\devices\core\appcfc\onApplicationStart_method.cfm
Type: cfml

```

**Comment by jeroenweareorangeeu** [comment]
Hi,

Yes, the URL should be '?appreload&reload=appreload&applydbupdates=true'

Try this again and let me know please.

**Comment by asimakos** [comment]
Yes, it worked! Thanks a lot.

**Comment by JonasEriksson** [comment]
Before I got to the TS werror message,, tryng to start up MasaCMS on a DB created on Digital OCean DB-Cluster (the 10 USD option-ish), I had to add 

SET @ORIG_SQL_REQUIRE_PRIMARY_KEY = @@SQL_REQUIRE_PRIMARY_KEY;
SET SQL_REQUIRE_PRIMARY_KEY = 0;

for it to go anywhere at all. What's the take on that?

Then, I got stuck on the same as the TS, applied the db update string mentioned and got to this now:

Table 'masahensel2024.tclassextendattributes' doesn't exist
Datasource:masahensel2024
SQL:select * from tclassextendattributes where 0=1
Code:0
Type:database
lucee.runtime.exp.DatabaseException: Table 'masahensel2024.tclassextendattributes' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:112)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:829)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:681)
	at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:345)
	at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:297)
	at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:243)
	at lucee.runtime.tag.Query.executeDatasoure(Query.java:1133)
	at lucee.runtime.tag.Query._doEndTag(Query.java:697)
