### ISSUE TITLE
syntax error in CF 2018 on startup

### ISSUE THREAD

**Issue by guustnieuwenhuis** [MasaCMS/MasaCMS#51]
### Discussed in https://github.com/MasaCMS/MasaCMS/discussions/48

Syntax should be 

`} catch(any e) {`
instead of 
`} catch (e) {`

<div type='discussions-op-text'>

<sup>Originally posted by **raybtwo** February 25, 2022</sup>
First, I just want to say that I am happy to see someone working on an open source version of Mura.

Initially I tried do a fresh install of Masa and got the following error:

ColdFusion was looking at the following text:

coldfusion.compiler.ParseException: Invalid CFML construct found on line 19 at column 27.
at coldfusion.compiler.cfml40.generateParseException(cfml40.java:20315)
at coldfusion.compiler.cfml40.jj_consume_token(cfml40.java:20183)
at coldfusion.compiler.cfml40.SimpleIdentifier(cfml40.java:10256)
at coldfusion.compiler.cfml40.catchStatement(cfml40.java:5708)
at coldfusion.compiler.cfml40.cfScriptTryStatement(cfml40.java:5602)
at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:2001)
at coldfusion.compiler.cfml40.cfscriptBlock(cfml40.java:3231)
at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1992)
at coldfusion.compiler.cfml40.ComplexStatement(cfml40.java:2090)
at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1978)
at coldfusion.compiler.cfml40.cfscriptBlock(cfml40.java:3231)
at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1992)
at coldfusion.compiler.cfml40.ComplexStatement(cfml40.java:2090)
at coldfusion.compiler.cfml40.cfscriptStatement(cfml40.java:1978)
at coldfusion.compiler.cfml40.cfscript(cfml40.java:1781)
at coldfusion.compiler.cfml40.processCfmlTags(cfml40.java:6563)
at coldfusion.compiler.cfml40.cfml(cfml40.java:6609)
at coldfusion.compiler.cfml40.start(cfml40.java:7194)
at coldfusion.compiler.NeoTranslator.parsePage(NeoTranslator.java:655)
at coldfusion.compiler.NeoTranslator.parsePage(NeoTranslator.java:635)
at coldfusion.compiler.NeoTranslator.parseAndTransform(NeoTranslator.java:457)
at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:407)
at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:160)
at coldfusion.runtime.TemplateClassLoader$TemplateCache$1.fetch(TemplateClassLoader.java:478)
at coldfusion.util.LruCache.get(LruCache.java:180)
at coldfusion.runtime.TemplateClassLoader$TemplateCache.fetchSerial(TemplateClassLoader.java:404)
at coldfusion.util.AbstractCache.fetch(AbstractCache.java:58)
at coldfusion.util.SoftCache.get_statsOff(SoftCache.java:153)
at coldfusion.util.SoftCache.get(SoftCache.java:92)
at coldfusion.runtime.TemplateClassLoader.findClass(TemplateClassLoader.java:672)
at coldfusion.runtime.RuntimeServiceImpl.getFile(RuntimeServiceImpl.java:1180)
at coldfusion.runtime.RuntimeServiceImpl.resolveTemplatePath(RuntimeServiceImpl.java:1132)
at coldfusion.tagext.lang.IncludeTag.setTemplate(IncludeTag.java:427)
at cfonApplicationStart_include2ecfm1188197984._factor0(C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\onApplicationStart_include.cfm:106)
at cfonApplicationStart_include2ecfm1188197984._factor1(C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\onApplicationStart_include.cfm:100)
at cfonApplicationStart_include2ecfm1188197984._factor48(C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\onApplicationStart_include.cfm:99)
at cfonApplicationStart_include2ecfm1188197984.runPage(C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\onApplicationStart_include.cfm:1)
at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:262)
at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:735)
at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:565)
at coldfusion.runtime.CfJspPage._emptyTcfTag(CfJspPage.java:4329)
at cfApplication2ecfc879601163$funcSETUPAPPLICATION._factor0(C:\ColdFusion2018\cfusion\wwwroot\cms71\admin\Application.cfc:185)
at cfApplication2ecfc879601163$funcSETUPAPPLICATION.runFunction(C:\ColdFusion2018\cfusion\wwwroot\cms71\admin\Application.cfc:178)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:554)
at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:448)
at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:399)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:372)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:288)
at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4175)
at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4155)
at cfframework2ecfc59868454$funcSETUPAPPLICATIONWRAPPER.runFunction(C:\ColdFusion2018\cfusion\wwwroot\cms71\admin\framework.cfc:1082)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:554)
at coldfusion.filter.SilentFilter.invoke(SilentFilter.java:47)
at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:485)
at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:448)
at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:399)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:372)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:288)
at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4175)
at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4155)
at cfframework2ecfc59868454$funcONAPPLICATIONSTART.runFunction(C:\ColdFusion2018\cfusion\wwwroot\cms71\admin\framework.cfc:439)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:554)
at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:448)
at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:399)
at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:372)
at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:288)
at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:830)
at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:613)
at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:438)
at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:115)
at coldfusion.runtime.AppEventInvoker.onApplicationStart(AppEventInvoker.java:238)
at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:418)
at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
at coldfusion.filter.PathFilter.invoke(PathFilter.java:162)
at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:96)
at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
at coldfusion.CfmServlet.service(CfmServlet.java:226)
at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:311)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:46)
at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:373)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:834)

Column: 27
Line: 19
Template: C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\setup_check.cfm
Type: SYNTAX

Column: 0
ID: CFINCLUDE
Line: 106
Raw Trace: at cfonApplicationStart_include2ecfm1188197984._factor0(C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\onApplicationStart_include.cfm:106)
Template: C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\onApplicationStart_include.cfm
Type: CFML

Column: 0
ID: CF_ONAPPLICATIONSTART_INCLUDE
Line: 100
Raw Trace: at cfonApplicationStart_include2ecfm1188197984._factor1(C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\onApplicationStart_include.cfm:100)
Template: C:\ColdFusion2018\cfusion\wwwroot\cms71\core\appcfc\onApplicationStart_include.cfm
Type: CFML

Next I tried upgrading an existing Mura installation by updating autoupdateurl in the config/settings.ini.cfm file to https://github.com/MasaCMS/MasaCMS/archive/main.zip then running Update Core. I got the same error message that I got above. Does anyone have any suggestions on how to resolve this?

Thanks!</div>

**Comment by guustnieuwenhuis** [comment]
resolved in version 7.3.1
